export const getGasCompanyUrl = '/test/controller/gasCompany/getGasCompanyMas.do' // 获取项目公司
export const getGasShopUrl = '/test/controller/gasShop/getGasShopMas.do' // 获取门店信息
export const saveLpgUserInfoUrl = '/test/controller/forGas/postGasUserInfoMas.do' // 提交LPG用户信息
export const getGasListUrl = '/test/controller/forGas/getGasListMas.do' // 获取门店瓶装气列表
export const getAddressListUrl = '/test/controller/lpgPubUser/getSendAddressListByUserIdMas.do' // 获取地址列表
export const updateAddressUrl = '/test/controller/lpgPubUser/updateLpgPubUserMas.do' // 修改地址
export const deleteAddressUrl = '/test/controller/lpgPubUser/deleteLpgPubUserMas.do' // 删除地址
export const setDefaultLpgAddressUrl = '/test/controller/lpgPubUser/updateLpgPubUserDefaultMas.do' // 设为默认LPG地址
export const getDefaultAddressUrl = '/test/controller/lpgPubUser/getSendAddressListByUserIdMas.do' // 获取默认LPG地址
export const postGasOrderUrl = '/test/controller/forGas/postGasOrderMas.do' // 提交订单
export const getGasOrderUrl = '/test/controller/forGas/getGasOrderListMas.do' // 获取订单列表
export const updateGasOrderUrl = '/test/controller/forGas/updateOrderGasMas.do' // 更新订单
export const getVerifyCodeUrlTest = '/test/user/sendsms3' // 获取验证码 测试环境
export const checkUserTest = '/test/user/checkUser' // 验证用户
export const getVerifyPicTest = '/test/controller/merchant/authCode.do' // 获取图形验证码

// export const getGasCompanyUrl = '/controller/gasCompany/getGasCompanyMas.do' // 获取项目公司
// export const getGasShopUrl = '/controller/gasShop/getGasShopMas.do' // 获取门店信息
// export const saveLpgUserInfoUrl = '/controller/forGas/postGasUserInfoMas.do' // 提交LPG用户信息
// export const getGasListUrl = '/controller/forGas/getGasListMas.do' // 获取门店瓶装气列表
// export const getAddressListUrl = '/controller/lpgPubUser/getSendAddressListByUserIdMas.do' // 获取地址列表
// export const updateAddressUrl = '/controller/lpgPubUser/updateLpgPubUserMas.do' // 修改地址
// export const deleteAddressUrl = '/controller/lpgPubUser/deleteLpgPubUserMas.do' // 删除地址
// export const setDefaultLpgAddressUrl = '/controller/lpgPubUser/updateLpgPubUserDefaultMas.do' // 设为默认LPG地址
// export const getDefaultAddressUrl = '/controller/lpgPubUser/getSendAddressListByUserIdMas.do' // 获取默认LPG地址
// export const postGasOrderUrl = '/controller/forGas/postGasOrderMas.do' // 提交订单
// export const getGasOrderUrl = '/controller/forGas/getGasOrderListMas.do' // 获取订单列表
// export const updateGasOrderUrl = '/controller/forGas/updateOrderGasMas.do' // 更新订单
// export const getVerifyCodeUrlTest = '/user/sendsms3' // 获取验证码 测试环境
// export const checkUserTest = '/user/checkUser' // 验证用户
// export const getVerifyPicTest = '/controller/merchant/authCode.do' // 获取图形验证码
